load syntax.maude
load ../semantics/semantics.maude

mod TEST is 
  including CONFIG .
  including ASSIGN-TASKS . 
  including PART-MATCH-GRIPPER .
  including PART-MATCH-FEEDER .
--- 
endm

---(
set trace on .
set trace condition off .
set trace substitution off .
---)

--- this is the normal running command to get all results:
search instance =>! X:Config .

--- get only one result
--- search [1] instance =>! X:Config .

--- use this to get all coalitions
--- rewrite[1] instance .

--- use this to get all valid coalitions (required-ops is empty)
--- rewrite[2] instance .

--- this is to see where the program is stuck:
--- search instance =>! X:[Config] .

--- changes made:
--- human3 added
--- gripper3 and gripper 4 added
--- a7 added


----(  Solution for gap2
  task1: human1
  task2: r3 g2 f1 pd1
  task3: r2 f2 pd2 g1
  task4: r1 pd3 f3 g5
  task5: a1 a7 f4 pd4 g4
  task6: human2

---)
