load syntax.maude
load ../semantics/semantics.maude

mod TEST is 
  including CONFIG .
  including ASSIGN-TASKS . 
  including PART-MATCH-GRIPPER .
  including PART-MATCH-FEEDER .
--- 
endm

---(
set trace on .
set trace condition off .
set trace substitution off .
---)

--- this is the normal running command to get all results:
search instance =>! X:Config .

--- get only one result
--- search [1] instance =>! X:Config .

--- use this to get all coalitions
--- rewrite[1] instance .

--- use this to get all valid coalitions (required-ops is empty)
--- rewrite[2] instance .

--- this is to see where the program is stuck:
--- search instance =>! X:[Config] .

--- changes made:
--- human3 added
--- gripper3 and gripper 4 added
--- a7 added

