load ../syntax/syntax.maude
load ../parts/parts.maude
load ../mras/mras.maude
---load ../assembly/gap1.maude
load ../assembly/gap2.maude
--- load ../assembly/lsai.maude

mod CONFIG is including CONFIGURATION .
---  including GAP1 .
  including GAP2 .
  op instance : -> Config .
---  eq instance =  <config> <mras> mras </mras> <gaps> gap1 </gaps> </config> .
  eq instance =  <config> <mras> mras </mras> <gaps> gap2 </gaps> </config> .

--- config contains 2 cells: mras and gap - they interact

endm

---red instance .

